# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# при запуске Travis создаст базу tracker. Необходимо для интеграционных тестов SqlTracker
services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту romankhiropulos@gmail.com если сборка упала
notifications:
  email:
    recipients:
      - romankhiropulos@gmail.com
    on_success: never # default: change
    on_failure: always # defa,,ult: always

env:
  global:
      - CODECOV_TOKEN="1637e265-6731-4d45-88be-c58f01c73750"